#!/bin/bash

echo "top10 country to country migration"
echo " ----------------------------"
psql -d plum_pipe -c "Select * FROM dwh.v_top10_country_to_country_migration"


echo "top 10 country to country remittances"
echo " ----------------------------"
psql -d plum_pipe -c "Select * FROM dwh.v_top10_country_to_country_remittances"


echo "top10 migration destinations"
echo " ----------------------------"
psql -d plum_pipe -c "Select * FROM dwh.v_top10_migration_destinations"

echo "top10 migration origins"
echo " ----------------------------"
psql -d plum_pipe -c "Select * FROM dwh.v_top10_migration_origins"

echo "top10 net outflows"
echo " ----------------------------"
psql -d plum_pipe -c "Select * FROM dwh.v_top10_net_outflows"

echo "top10 net inflows"
echo " ----------------------------"
psql -d plum_pipe -c "Select * FROM dwh.v_top10_net_inflows"


