#!/bin/bash

echo "renaming column in remittance table"
echo "-----"
psql -d plum_pipe -c "ALTER TABLE load.remittance RENAME COLUMN receiver_id TO idonttellpeoplewhenimchangingcoreinfrastructure"

cd etl

echo "attempting to insert to column with same csv"
echo "-----"
echo "pythons response iiisss....."

pipenv run python3 ingest_csv.py --source data/remittance.csv --target_schema load --target_table remittance


echo "------"

psql -d plum_pipe -c "ALTER TABLE load.remittance RENAME COLUMN idonttellpeoplewhenimchangingcoreinfrastructure TO receiver_id"


echo "changing back and trying again"
echo "python response iiisss...."

pipenv run python3 ingest_csv.py --source data/remittance.csv --target_schema load --target_table remittance



